[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm@latest", "cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter web build"]

[start]
cmd = "node dist/my-web/server/server.mjs"
